// This is the default test file generated by Flutter.
// Custom tests for the IM app would go here.
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('App smoke test', (WidgetTester tester) async {
    // Placeholder — full widget tests would require mocking the ConnectionService
    expect(1 + 1, equals(2));
  });
}
